# This is a basic workflow to help you get started with Actions
name: Build Pull Request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Maven
        run: mvn -B package
      - name: Archive artifacts (Geyser Standalone)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Geyser Standalone
          path: bootstrap/standalone/target/Geyser.jar
      - name: Archive artifacts (Geyser Bukkit)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Geyser Bukkit
          path: bootstrap/bukkit/target/Geyser-Bukkit.jar
      - name: Archive artifacts (Geyser BungeeCord)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Geyser BungeeCord
          path: bootstrap/bungeecord/target/Geyser-BungeeCord.jar
      - name: Archive artifacts (Geyser Sponge)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Geyser Sponge
          path: bootstrap/sponge/target/Geyser-Sponge.jar
      - name: Archive artifacts (Geyser Velocity)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Geyser Velocity
          path: bootstrap/velocity/target/Geyser-Velocity.jar
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
